* 《批判性思维工具》摘要--绪论(三）

** 批判性思维的概念

批判性：建立在某些标准上，对事物的好坏的进行恰当判断。
批判性思维是指，为了提高我们的思维水平而对自身思维进行的系统性监视。当我们
批判性地进行思考的时候，我们不能从它的表面价值进行评定，我们必须清晰地，准
确地，相关地，有深度，有广度和有逻辑性地对思维进行分析和评价。我们发现所有
的推理都发生在观点和参考框架中，这些推理都是由一定的目标引发，并具有一定的
信息基础，用来推理的所有信息和数据都必须能够被解释，这些解释涉及概念，这些
概念需要假设，思维中使用的基本参考信息都有一定的意义。思维中的缺陷可能发生
在思维过程中的任何一个阶段。因此我们要密切注视思维的每一方面。
为什么批判性思维如此重要

** 批判性思维的常用质疑

-  这里最基本的问题是什么？
-  我应该用哪种观点来思考这一问题？
-  这样假定对我来说有没有意义？
-  我能从这些数据中作出哪些合理的推论？
-  这些图形有什么含义？
-  这里最基本的概念是什么？
-  这些信息与那些信息一致吗？
-  什么原因使问题变得复杂？
-  怎样才能检验这些数据的准确性？
-  这是一个可靠的信息来源吗？

** 成为自己思维的批判者   

你可以为自己做的最重要，最有意义的事情就是开始批判性地思考自己的思维方式。
这么做并不是否定自己，而是对自己的完善。这样做能够是练习思维技能的开始。是
终生学习的开端。为了成为自己思维的批判者，你首先要觉察到自己的思维方式，了
解它的结构，观察它的含义，找出它的基础和优缺点。你必须认识到，只有通过精力
投入和刻苦练习，你才能够彻底改变你的思维方式。你需要了解你思维的缺点以及你
努力想要学习的优点。无论你现在的思维处于哪个层次，你要明白通过努力你可以改
善自己的思维。批判性思考者努力的最终目标就是促进自己思维创造性地进步。

** 建立新的思维方式

批判性思维要求思考者必须清楚自己的目标，然后才能使用批判性思维提供的各种工
具来提高思维质量:

一种有目的的思维方式 :: 用于学习上或生活中的任何问题
在批判性思维中，思考者可以系统地，习惯性地使用各种思维特质::例如在思维上的
持之以恒，思维上的谦逊，换位思考和思维公正性
控制思维的结构::了解思维的成分，包括问题，信息，概念，推论，假设，意义和观
点

使用思维标准来检验思维::例如，清晰性，准确性，精确性，相关性，深度，广度，
逻辑性和公正性
不断提高思维质量::使思维方式更加清晰，准确，精确，更有深度和广泛性，更加有
逻辑性，相关性和重要性。并更加公正。

** 培养对自己推理能力和识别事物能力的信心

思维的力量是无穷的，如果我们想要发掘自己的潜力，我们必须掌控自己的思维。

标准化的智力测验常常成为学习的阻碍，那些反应最快的学生视自己的智力为骄傲，
而那些看起来反应慢的学生常常认为自己是不重要的，从而轻易放弃了学习。他们不
明白龟兔赛跑的道理。是否掌握了知识并不重要，关键看是否注重提高并控制自己的
思维方式。


优秀的思考者可能是那些一直辛勤地工作，经常提问，追求重要观点，综合思考各种信息
区分地对待事物，试图在重要的思想观点之间建立联系的人。他们对自己的思维有强烈的
信心，他们享受学习和思考过程中，不同观点的碰撞交锋。

end
(2017.12.01.30分钟）
(2017.12.13.50分钟)
