* 《批判性思维工具》成为公正的思考者--(一）

** 人的本性是自私的
人的本性是自私的。思维不是与生俱来就是公正的，要想做到公正需要养成特定的
思维特质-谦逊，勇气，整合性，自主性，换位思考，坚毅以及对推理的信心。

批判性思维可能走向两个完全不同的方向：自我中心或公正。当我们学习批判性思
维所需要的思维技巧时，我们既可以自私地使用这些技巧，也可以公正地使用他们。

批判性较弱的思考者传统上被称为诡辩家，诡辩是一种以赢得辩论为目的的思维技巧
它不管思维中是否存在问题，也不管相关的观点是否被忽略了。诡辩性思维的目的就
是要赢。诡辩的思考者使用低水平的言辞和论证，使得不合理的思维看起来合理，使
合理的思维看起来不合理。诡辩性思维是律师，法庭原告和一些政客经常使用的思维
方式，对于这些人，他们更关心的输赢而不是公正。他们利用思维技巧诡计操纵人们
的情感和观点。

只要没有遇到批判性思维更强的思考者，诡辩者就能赢。批判性程度强的思考者不会
轻易地被圆滑，诡辩的言辞和思维诡计所蒙蔽。批判性强的思考者最鲜明的特点是对
公平正义的追求。

批判性思考者具有如下特征：

不容易被外界干扰，不会轻易相信某人的唯一论断，总是考虑事情的各种可能性，不
论处理的事情是十分确定的还是十分复杂的。都能权衡不同证据，能够抵抗住偏见的
影响。

世界上有太多自私的思考者，太多的诡辩家，欺骗家，太多不道德的律师，政客他们
擅长歪曲信息来服务他们自身的利益。我们需要称为一个技能熟练且公正的思考者，
一个能够甄别那些损害他人利益的诡辩游戏的思考者。

** 公正性需要什么



** 批判性思维的常用质疑

-  这里最基本的问题是什么？
-  我应该用哪种观点来思考这一问题？
-  这样假定对我来说有没有意义？
-  我能从这些数据中作出哪些合理的推论？
-  这些图形有什么含义？
-  这里最基本的概念是什么？
-  这些信息与那些信息一致吗？
-  什么原因使问题变得复杂？
-  怎样才能检验这些数据的准确性？
-  这是一个可靠的信息来源吗？

** 成为自己思维的批判者   

你可以为自己做的最重要，最有意义的事情就是开始批判性地思考自己的思维方式。
这么做并不是否定自己，而是对自己的完善。这样做能够是练习思维技能的开始。是
终生学习的开端。为了成为自己思维的批判者，你首先要觉察到自己的思维方式，了
解它的结构，观察它的含义，找出它的基础和优缺点。你必须认识到，只有通过精力
投入和刻苦练习，你才能够彻底改变你的思维方式。你需要了解你思维的缺点以及你
努力想要学习的优点。无论你现在的思维处于哪个层次，你要明白通过努力你可以改
善自己的思维。批判性思考者努力的最终目标就是促进自己思维创造性地进步。

** 建立新的思维方式

批判性思维要求思考者必须清楚自己的目标，然后才能使用批判性思维提供的各种工
具来提高思维质量:

一种有目的的思维方式 :: 用于学习上或生活中的任何问题
在批判性思维中，思考者可以系统地，习惯性地使用各种思维特质::例如在思维上的
持之以恒，思维上的谦逊，换位思考和思维公正性
控制思维的结构::了解思维的成分，包括问题，信息，概念，推论，假设，意义和观
点

使用思维标准来检验思维::例如，清晰性，准确性，精确性，相关性，深度，广度，
逻辑性和公正性
不断提高思维质量::使思维方式更加清晰，准确，精确，更有深度和广泛性，更加有
逻辑性，相关性和重要性。并更加公正。

** 培养对自己推理能力和识别事物能力的信心

思维的力量是无穷的，如果我们想要发掘自己的潜力，我们必须掌控自己的思维。

标准化的智力测验常常成为学习的阻碍，那些反应最快的学生视自己的智力为骄傲，
而那些看起来反应慢的学生常常认为自己是不重要的，从而轻易放弃了学习。他们不
明白龟兔赛跑的道理。是否掌握了知识并不重要，关键看是否注重提高并控制自己的
思维方式。


优秀的思考者可能是那些一直辛勤地工作，经常提问，追求重要观点，综合思考各种信息
区分地对待事物，试图在重要的思想观点之间建立联系的人。他们对自己的思维有强烈的
信心，他们享受学习和思考过程中，不同观点的碰撞交锋。

优秀的思考者有一些共同特征，他们会系统认真地思考自己解决问题的方式，会对自己不
理解的问题进行提问，他们不关心对他们智力水平的界定，也不理会智力试验的结果。他
们认为，无论记忆好坏，反应快慢，学习最重要的是坚持不懈的投入，以及在学习过程中
掌握优秀思维的技巧。只要去做，个体就能养成优秀的思维技巧。成为赢得龟兔赛跑的乌
龟吧。

end
(2017.12.01.30分钟）
(2017.12.13.50分钟)
